### ISSUE TITLE
USER STORY: View Paginated List of Posts

### ISSUE THREAD

**Issue by techistem** [techistem/UkMove_CI_P4#15]
As a site user **I can** view a paginated list of posts so that **I can** select the post I want to view

- Given more than one post in the database, these multiple posts are listed
- When a user opens the main page a list of posts is seen
- Then the user sees all posts titles with pagination to choose what to read

## Tasks
- [ ] Create a view to display posts from the database.
- [ ] Add pagination to limit the number of posts shown per page.
- [ ] Update the template to display posts with pagination controls.
